name: Python checks

on:
  push:
  pull_request:
  workflow_dispatch:


jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --frozen
      
      - name: Generate protobuf files
        run: bash .scripts/compile-grpc.sh
      
      - name: Check syntax / compile
        run: uv run python -m compileall .
      
      - name: Check tests
        run: uv run pytest
